service: default
runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /
    static_files: dist/torqata-poc/index.html
    upload: dist/torqata-poc/index.html
  - url: /
    static_dir: dist/torqata-poc
  - url: /.*
    static_files: dist/torqata-poc/index.html
    upload: www/(.*)
    
skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE